version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: collaborative-postgres
    environment:
      POSTGRES_DB: collaborative_publishing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - collaborative-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for BullMQ
  redis:
    image: redis:7-alpine
    container_name: collaborative-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - collaborative-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  collaborative-network:
    driver: bridge 